trigger:
- refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    VERSION_TAG=`git describe --tags`
    VERSION_TAG=${VERSION_TAG:1}
    echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
  displayName: Parse version from tag v*
  
- task: UseDotNet@2
  displayName: Install .NET
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: DotNetCoreCLI@2
  displayName: Restore NuGet
  inputs:
    command: 'restore'
    projects: |
      Cloudy.CMS/Cloudy.CMS.csproj
      Cloudy.CMS.UI/Cloudy.CMS.UI.csproj
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: Build projects
  inputs:
    command: 'build'
    projects: |
      Cloudy.CMS/Cloudy.CMS.csproj
      Cloudy.CMS.UI/Cloudy.CMS.UI.csproj

- task: DotNetCoreCLI@2
  displayName: Pack NuGet
  inputs:
    command: 'pack'
    packagesToPack: 'Cloudy.CMS/Cloudy.CMS.csproj;Cloudy.CMS.UI/Cloudy.CMS.UI.csproj'
    nobuild: true
    includesymbols: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'VERSION_TAG'

- task: NuGetCommand@2
  displayName: Push NuGet
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Cloudy.CMS nuget.org'

- task: Docker@2
  displayName: Build static files
  inputs:
    containerRegistry: 'ACR bjorngoranssoninvest'
    repository: 'cloudy-cms-ui-static-files'
    command: 'buildAndPush'
    Dockerfile: 'Cloudy.CMS.UI/wwwroot/Dockerfile'
    tags: '$VERSION_TAG'