trigger:
- refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

steps:



- script: |
    VERSION_TAG=`git describe --tags`
    echo "First step: $VERSION_TAG"
    VERSION_TAG=${VERSION_TAG:1}
    echo "Second step: $VERSION_TAG"
    echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
    echo Add other tasks to build, test, and deploy your project.
  displayName: 'Run a multi-line script'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'Cloudy.CMS/Cloudy.CMS.csproj;Cloudy.CMS.UI/Cloudy.CMS.UI.csproj'
    nobuild: true
    includesymbols: true
    versioningScheme: 'off'